### ISSUE TITLE
Require but include string as well?

### ISSUE THREAD

**Issue by michalss** [Rohansi/Mond#111]
Hi,

Since im not using files but DB for scripts i would like to ask you if there is a way to do include scripts from other source than file polease?
I know there is function require but it will only take file, but i would like to make this to take also the string as script.

Regards

**Comment by Rohansi** [comment]
You should be able to either:
1. Bind a function that runs the script from a string
2. If you want it to specifically go through `require`, then you can configure the `RequireLibrary` to set a custom `Resolver` and/or `Loader`

```cs
var state = new MondState();
state.Libraries.Configure(libraries =>
{
    var requireLibrary = libraries.Get<RequireLibrary>();
    requireLibrary.Resolver = (name, directories) =>
    {
        // This needs to return the string to pass to the loader (usually a file path, but can be any string)
        return "resolved-module";
    };

    requireLibrary.Loader = resolvedName =>
    {
        // This needs to return the module source text to load into the state, so you can load it from the DB here
        return "exports.foo = 'bar';";
    };
});
```
