### ISSUE TITLE
Require does not work for me.

### ISSUE THREAD

**Issue by michalss** [Rohansi/Mond#113]
Hello,

Icannot make require function work. No error nothing returns back to me. Can you add some error handling what is wrong and why it does not pick the files please?

For Example:
```
var dec = require("Decorations_2");
```

but how to do decorations in the scriopt if they are from require functions ?
```
//THIS IS ORIGINAL SCRIPT
@class
const TextHandlerLitter = {

//NOT WORK
@dec.class
const TextHandlerLitter = {

```
not sure what is right

Thx

**Comment by Rohansi** [comment]
You need to export the functions from your module to make them available. You can do that like so:

```
exports.printObject = fun printObject(data) {
   printLn(Json.serialize(data));	
}
```
or
```
fun printObject(data) {
   printLn(Json.serialize(data));	
}
return {
   printObject,
};
```

I need to write up some documentation for this.

I think I'll also add an `export` modifier keyword to simplify this.

**Comment by Rohansi** [comment]
> thx a lot, this works perfectly :)

Great! Do you have any other questions @michalss? 😄

**Comment by Rohansi** [comment]
There are no built-in `require` modules. By default `require` just loads additional code into Mond from files on disk.

However, there is `Seq.mnd` in the examples folder. That's a module which provides most if not all of the LINQ-style methods from C#. You'll need to download `Seq.mnd`, `Seq.Scalar.mnd`, and `Seq.Sorting.mnd` and then you can `require('Seq.mnd')` to use it.

It's used in the example from the readme:
```kotlin
const Seq = require("Seq.mnd");

const randomApi =
    "https://www.random.org/decimal-fractions/?num=1&dec=9&col=1&format=plain";

Async.start(seq() {
    // concurrently request for 10 random numbers
    var numberTasks = Seq.range(0, 10)
        |> Seq.select(() -> Http.getAsync(randomApi))
        |> Seq.toArray();

    // wait for all the requests to finish
    var numbers = yield Task.whenAll(numberTasks);

    // parse and sum the numbers
    var total = numbers
        |> Seq.select(s -> Json.deserialize(s))
        |> Seq.aggregate(0, (acc, n) -> acc + n);
        
    printLn("average = {0}".format(total / 10));
});

Async.runToCompletion();
```
