### ISSUE TITLE
Use console library inside own Module

### ISSUE THREAD

**Issue by michalss** [Rohansi/Mond#115]
HI @Rohansi , me again :)

Can you please help me out once again. Is there a way to use build in lib ConsoleOutput in my own modules? I would like to monitor long proccess and print out some logs during the process.

Thank you

**Comment by Rohansi** [comment]
The `print` and `printLn` functions are already available to all Mond modules.

Do you maybe mean you want to call the same functions from your own C# library? There's no way to get one `IMondLibrary` from another but you can configure your library to use the same `TextWriter` as the `ConsoleOutputLibrary`.

```cs
state.Libraries.Configure(libs =>
{
    var console = libs.Get<ConsoleOutputLibrary>();
    console.Out = System.Console.Out; // can change to something else

    var otherLibrary = libs.Get<MyCustomLibrary>();
    otherLibrary.Out = console.Out; // pass your library the same output location
});
```

Then you can use the same `TextWriter` from your C# library code.

Refer to [`ConsoleOutputLibrary`](https://github.com/Rohansi/Mond/blob/63b221917d93e41f7361542937e4f92f8788510b/Mond/Libraries/ConsoleLibraries.cs#L19-L35) and the [`ConsoleOutput` module](https://github.com/Rohansi/Mond/blob/63b221917d93e41f7361542937e4f92f8788510b/Mond/Libraries/Console/ConsoleOutput.cs) for how to set this configuration up.
