### ISSUE TITLE
Async Examples and make sure it does not block the thread.

### ISSUE THREAD

**Issue by michalss** [Rohansi/Mond#116]
Hello,

I do have a more question about asyncs. Using avaloniaui and i would like to make sure it when i run long-running task, it won't block the UI thread. I did try many different options, but i cannot figure it out. It always blocks the UI Thread. Can you please make more examples how to utilize the async in mond please ? I might be able to find the correct approach with async..

https://github.com/Rohansi/Mond/wiki/Async-Library

thank you

**Comment by Rohansi** [comment]
The important thing to remember is when you run Mond code from C# then that will block until whatever you ran completes. Starting async tasks (`Async.start`) and `yield`ing async taaks will not block but `Async.runToCompletion` will block.

Instead of using `Async.runToCompletion` you should periodically call `Async.run` from the UI thread to process any pending tasks. So you would have something like this:
```cs
// one-time initialize somewhere (cache this to not have Mond compile the string all the time)
var asyncRunFunc = state.Run("return () => Async.run();");

// then run this in a UI thread timer
state.Call(asyncRunFunc);
```

This should work if you are using async for everything.

**Comment by Rohansi** [comment]
Sorry for the delay, try this:
```cs

   StringBuilder sb = new();
        try
        {
            await Dispatcher.UIThread.InvokeAsync(async () =>
            {
                var state = new MondState
                {
                    Libraries =
                    {
                        new JsonLibraries(),
                        new ConsoleLibraries(),
                        new LitHandler.Library(),
                        new LitModule(),
                        new IOMoudule(),
                        new ConvertorsManual(),
                        new GenericModule()
                    },
                };

                state.Libraries.Configure(libs =>
                {
                    var consoleOutput = libs.Get<ConsoleOutputLibrary>();
                    App.ConsoleOutputLibrary = consoleOutput;
                    consoleOutput.Out = new StringWriter(sb)
                    {
                        NewLine = "\n"
                    };
                });

                var asyncRunFunc = state.Run($"return () => Async.run();");

                sb.AppendLine($"###### Script Execution at: [{DateTime.Now.ToString("HH:mm:ss.fff")}] ######\n");
                var result = state.Run($"{_textEditor.Document.Text}");
                
                while (state.Call(asyncRunFunc)) // returns false when no async tasks are running
                {
                    await Task.Delay(10);
                }

                sb.AppendLine($"\n###### Script End at: [{DateTime.Now.ToString("HH:mm:ss.fff")}] ######");

                //PrintLog(result.Serialize());
                PrintLog(sb.ToString());
            }, DispatcherPriority.Background);


            SharedService.AppStateMessage = "End Script...";
        }
        catch (MondException exception)
        {
            PrintLog(exception.Message);
        }
```

**Comment by Rohansi** [comment]
Sorry, it should be this:
```cs
var asyncRunFunc = state.Run($"return () -> Async.run();");
```

**Comment by Rohansi** [comment]
> but still thinking how to handle during the task console output.. It wont print anything until task is finnished. Is it even possible ?

Yes, you can make your own class extending [`TextWriter`](https://learn.microsoft.com/en-us/dotnet/api/system.io.textwriter?view=net-8.0) and then you can write it to your UI immediately.

```cs
class OutputTextWriter : TextWriter
{
    public override void Write(string str)
    {
        // todo: add text to the output window
    }

    public override void WriteLine()
    {
        // todo: write a line to the output window
    }
}
```

Then you can set `ConsoleOutputLibrary.Out` to an instance of that custom `TextWriter` and it will be called as soon as `print` and `printLn` are called in Mond.

**Comment by Rohansi** [comment]
You could have passed a reference to your view into the constructor for `OutputTextWriter` but that works too!
