### ISSUE TITLE
'Reverse' pipeline operator proposal.

### ISSUE THREAD

**Issue by SirTony** [Rohansi/Mond#29]
I thought it'd be prudent to get feedback on this idea before anything gets implemented and pull requests opened. Because this idea is admittedly quite niche, simple though it is. Although if the array prototype had methods like `map`/`filter` & co I could see it having a much stronger use case.

The idea is to add a new operator similar to pipeline, except it points in the other direction and works in reverse. The function call is on the left, the value to be passed is on the right, and rather than inserting the value as the first parameter, it inserts it as the last parameter.

The main inspiration behind this is Ruby's blocks, as it would allow Mond to emulate this to a degree.

``` ruby
def qsort( collection, &comparer )
    ...
end

strings = [ "Watermelon", "Apple", "Grape", "Pear", "Honeydew" ]
sorted  = qsort( strings ) do | a, b |
    # Do some super-complex comparison magic
    a.length - b.length
end
```

``` javascript
fun qsort( collection, comparer ) {
    ...
}

var strings = [ "Watermelon", "Apple", "Grape", "Pear", "Honeydew" ];
var sorted  = qsort( string ) <| fun( a, b ) {
    // Even more magic
    return a.length() - b.length();
}
```

**Comment by Rohansi** [comment]
I'm not sure what problem this is meant to solve, could you come up with a better example?

**Comment by SirTony** [comment]
As I mentioned above, it's more niche than problem-solver. Closer to syntax sugar than anything else, mainly allowing an anonymous function or lambda to be separated from the argument list of a function call, which would be most useful for array prototype functions like `map`, `filter`, and `reduce`, which take a callback as their only argument and apply it to each element of the sequence.

Another example could be a slightly more complex filtering algorithm to collect a list of file names.

``` javascript
// List all .cs files in the current directory
// that don't contain pre-processor directives
var files = Directory.getFiles( "./*.cs" ).filter() <|
fun( name ) {
    var lines = File.readAllText( name )         // Read file contents into memory
                    .split( "\n" )               // Split on LF
                    .map( line -> line.trim() ); // Map each line through a lambda
                                                 // that trims all whitespace off both ends
     
    foreach( var line in lines ) { // Iterate the sanitized lines
        if( line.startsWith( "#" ) )
            return false; // Reject the file if any of the lines start with '#'
    }

    return true; // Otherwise accept the file.
};
```

**Comment by Rohansi** [comment]
I'm still not sure about it. The only advantage I see from this is the function call's closing parenthesis can stay with the call. I don't think it's very useful to chain `<|` either.

If there was a better example for this I'd be up for it, but right now it looks like it only lets you type a bit more to keep the closing parenthesis with the call.
