### ISSUE TITLE
Language Inconsistencies

### ISSUE THREAD

**Issue by dajoh** [Rohansi/Mond#30]
Currently I see two pretty major inconsistencies in Mond, one having to do with functions inside objects, and the other having to do with list comprehensions.

Generally in Mond, when you create a function or a sequence using the `fun`/`seq` keywords a declaration is made. This means that code like this is valid and works:

```
var x = banana(fun bap() { return true; }, y, z);
bap();
```

This however, is not the case with object literals. This code is invalid, as no declaration is made for `bap`:

```
var x = { fun bap() { return true; } };
bap();
```

List comprehensions are inconsistent both in syntax and semantics. They're inconsistent syntactically because generators inside list comprehensions syntactically look like `x in list` compared to `var x in list` in `foreach` loops. They're inconsistent semantically because the 'core' expression of a list comprehension can refer to declarations before they physically appear in the source file, and inside list comprehensions is the only time in Mond where you can do that. Example:

```[x : x in list]```

I suggest the follow changes be made to Mond:
* Object literals should only allow key-value syntax.
  * Intead do: `add: (a, b) -> { ... }` or `add: fun (a, b) { ... }`.
* List comprehensions should be removed all together from the language. While I do think it's a cool feature (I was even the one to suggest it in the first place), I don't think it has much use.

**Comment by dajoh** [comment]
I've talked to @Rohansi privately and he agrees with me, but we'd like @SirTony's opinion too.

**Comment by SirTony** [comment]
I find myself agreeing on both accounts.

However, I notice you don't touch on the first code sample again after bringing it up. The fact that such a thing is even valid I find a little odd. Not even JavaScript allows that.

``` javascript
function foo( cb ) {
   return cb();
}

foo( function bar() { return true; } );
bar(); // ReferenceError: bar is not defined
```

I'd further suggest having function literals declared with `fun` and `seq` as statements, but require them to have names, while also having them as expressions and require that they **not** have names, which would make the first of your snippets a syntax error, but allow this: `foo( fun() { return true; } );`. Lambdas are unaffected.

**Comment by dajoh** [comment]
I agree with that change aswell.

**Comment by Rohansi** [comment]
Okay, so these are the changes you've come up with:

1. Remove the function/sequence shorthand in object literals. I only really added this because it gave better stack traces than doing `test: fun () { ... }`. I can do that without new syntax though, so removing it is fine.
2. Remove list comprehensions. I think this is good. I doubt anything but the example code uses it.
3. Make function statements require names and make function expressions require no name. This is good, it's very strange behavior that can be removed.

If I missed anything please let me know. I'm almost done making these changes.
