### ISSUE TITLE
Adding __gte, __lt, and __lte metamethods.

### ISSUE THREAD

**Issue by SirTony** [Rohansi/Mond#61]
Having `__gt` (and `__eq`) also do the work of `>=`, `<`, `<=` potentially makes using metamethods more confusing and restrictive for little gain. The main problem is that it makes it impossible to target specifically `<`, `<=`, and `>=` for different functionality from `>`, or disallowing the use of `>` entirely, meaning that overloading the comparison operators for completely different functionality (similarly to how C++ overloads the shift operators for streams) is of little usefulness when `<` and `>` end up calling the same function.

Admittedly this only really become a problem when working on mapping .NET operator overloads to metamethods for SirTony/Mond.BindingEx#3 because the CLR allows overloading all four separately.

**Comment by Rohansi** [comment]
Yeah, only having `__gt` and `__eq` is kinda shitty. We should definitely do this.
