### ISSUE TITLE
Remove right side dispatch from relational metamethods

### ISSUE THREAD

**Issue by Rohansi** [Rohansi/Mond#64]
Relational operators can currently dispatch on the right hand side when it is an object. This behavior is inconsistent with #47 but I'm not really sure if it's the best decision.

@SirTony What are your thoughts on this? #63 copies the RHS dispatch from `__gt` but doesn't implement it properly, but I feel like it just shouldn't be supported.

**Comment by SirTony** [comment]
I feel like consistency is the best policy, and just dropping RHS-dispatch to keep it in line with #47 is the way to go. Then the implementation of the comparison operators can just be changed to let the LHS decide what the RHS coerces to (as with the other binary operators).

An alternative solution could be borrowing from D and allowing right-hand metamethods to be implemented separately.

For example:

```d
struct Foo
{
    immutable int x;

    this() @disable;
    this( int x ) { this.x = x; }

    Foo opBinary( string op )( int y ) if( op == "+" ) { return Foo( this.x + y ); }
    Foo opBinaryRight( string op )( int y ) if( op == "-" ) { return Foo( y - this.x ); }
}

auto a = Foo( 1 );
auto b = a + 9;  // Foo where x == 10
auto c = 15 - b; // Foo where x == 5
```

```
fun Foo( x ) {
    return {
        __add: y -> Foo( x + y ),
        __rsub: y -> Foo( y - x )
    };
}

const a = Foo( 1 );
const b = a + 9;  // Foo where x == 10
const c = 15 - b; // Foo where x = = 5
```

Although that might be getting too complicated for little benefit.

**Comment by Rohansi** [comment]
Yeah, having almost twice the amount of metamethods is a bit much. Yoda conditions are shit anyway.
