### ISSUE TITLE
How can I get all global variables?

### ISSUE THREAD

**Issue by tiksn** [Rohansi/Mond#77]
I am creating calculator with Mond and Avalonia. I want to see all global variables on right side. How can I do that? how can I enumerate variables?

Currency I am using hack like this

```C#
var globalVariables = state.Run("return global;").Object.Where(x=>x.Value.Type != MondValueType.Function && x.Value.Type != MondValueType.Object);
```

but it lokks and feels wrong.

**Comment by Rohansi** [comment]
Sorry for the late reply. Unfortunately it looks like there's no way to get the `global` object directly right now. I'll add one in so you can use that instead. Thank you!
