### ISSUE TITLE
How to add list / array to mondState?

### ISSUE THREAD

**Issue by jwieneke** [Rohansi/Mond#78]
Hi,

is there any possibility to add a list or an array to `MondState`?

```csharp
var mondState = new MondState();
mondState["global.strValue"] = "my string value";
mondState["global.arrayValue"] = new List<string>();
```

Line 2 works fine, but in line 3 I get a compiler error `Cannot implicitly convert type 'System.Collections.Generic.List<string>' to 'Mond.MondValue'`.
I could not find any information about how to convert `List<string>` to `Mond.MondValue` in the documentation.

Any help is appreciated. :-)

**Comment by SirTony** [comment]
You can construct a new empty array like so:

```javascript
var empty = new MondValue( MondValueType.Array );
```

You can also construct a non-empty array:

```javascript
var oneToTen = new MondValue( Enumerable.Range( 1, 10 ).Select( x => new MondValue( x ) );
```

**Comment by Rohansi** [comment]
Thanks @SirTony!

That constructor is a bit of a nightmare and should be replaced with some more descriptive static methods on `MondValue`. But for now it will do.

To elaborate on non-empty arrays, they need to be `List<MondValue>` so you could do the following:
```csharp
var numbers = new List<MondValue>();

for (int i = 0; i < 10; i++)
{
    var aNumber = new MondValue(i); // everything in Mond is a MondValue! numbers, strings, etc.
    numbers.Add(aNumber);
}

mondState["arrayValue"] = new MondValue(numbers);
```

If you want to change the array later you can get the `List<MondValue>` by using the `Array` property (for example `numbers.Array.Add(anotherNumber);`).

Also @jwieneke you don't need the "global." there when setting up the state. Everything in the state is already global so it is assumed for you. Less typing!

Thank you for trying Mond!
