### ISSUE TITLE
How debugger work?

### ISSUE THREAD

**Issue by haifenghuang** [Rohansi/Mond#81]
Hi, Rohansi:
    I want to study how the debugger works. When I start the REPL with `--debug` arguments, the program just exit normally. Below is the image:

![imag](https://user-images.githubusercontent.com/4425219/77722754-9a204e80-7029-11ea-9250-8b4a56544201.png)

**Comment by haifenghuang** [comment]
BTW, could you kindly give me some hints on the architecture of the debugger? For example, when the client presses 'next', How did you know that the code will execute the `if` branch or `else` branch?

Assume that the only one `breakpoint` is on `var n = 10` and the current execution statement is on `if (n > 10)` , now when user presses `next`, it will jump to the `else` block instead of `if` block.

```
var n = 10;
if (n > 10) {
    printLn("n > 10");
}
else {
    printLn("n <= 10");
}
```

**Comment by Rohansi** [comment]
Sorry for the late reply. When you add `--debug` it only enables the debugger. The program will run as normal unless instructed to break or it hits a `debugger` statement.

The Mond debugger basically hooks into the bytecode interpreter loop that runs all Mond programs. [That code mostly lies here.](https://github.com/Rohansi/Mond/blob/master/Mond/VirtualMachine/Machine.cs#L100-L981) It's a monster but search for `Debugger` to see where it hooks in. There's a bit at the start of the loop, a bit when calling functions in Mond, a bit when returning from functions, and the bit for the `debugger` statement. Those call into an implementation of the `MondDebugger` class which can do whatever it wants.

To actually map lines to the code, or to highlight which code it is executing, that needs compiler integration. The `--debug` flag also enables generating additional information while compiling the code. It's commonly called sequence points. This lets us map from bytecode positions into lines of code and ranges of text. It also tells the debugger where to pause when you press step.

So, to answer how it knows to jump to the `else` block, that's just what the bytecode did. It jumped into the `else` block, and then the debugger mapped that new bytecode position into the line inside the `else` block.

**Comment by haifenghuang** [comment]
Thanks a lot for the explanation.
