### ISSUE TITLE
No clear documentation or feature on calling a function, binding a class, or overriding a function without global

### ISSUE THREAD

**Issue by Nuciloco** [Rohansi/Mond#93]
I'm trying to call a function from a script, for example, ``fun testFunction``.
I want to call this function without calling ``global.testFunction`` on my own script``.

I also saw it was possible to bind your own c# class as well but again, according to the documentation. This only allows the class to be called from ``var newCustomClass = global.customClass("Test")`` instead of calling it like this ``var newCustomClass = customClass("Test")``

**Comment by Rohansi** [comment]
Hey @Flairieve! Thanks for bringing this to my attention. This is indeed possible to do right now but missing from the documentation.

You need to define a 'library' like this, implementing `IMondLibrary` and returning the bindings with the name you want: https://github.com/Rohansi/Mond/blob/2a732c36690e6462f95586e2e3a345b3619cc266/Mond/Libraries/ConsoleLibraries.cs#L47-L70

You'll also need to define a library collection by implementing `IMondLibraryCollection`: https://github.com/Rohansi/Mond/blob/2a732c36690e6462f95586e2e3a345b3619cc266/Mond/Libraries/ConsoleLibraries.cs#L25-L34

Then instantiate your `IMondLibraryCollection` and add it to your `MondState` like so:
```csharp
var state = new MondState
{
    Libraries =
    {
        new MyAwesomeLibraries(),
    }
};
```

**Comment by Rohansi** [comment]
Implementing `IMondLibraryCollection` is optional as of e44895ca7fcf0c0b619aacf3000417ab543b0017. Will write up docs.

**Comment by Rohansi** [comment]
Added a wiki page for this here https://github.com/Rohansi/Mond/wiki/Custom-Libraries

Thank you!
