### ISSUE TITLE
General questions regarding sandboxing and performance

### ISSUE THREAD

**Issue by lofcz** [Rohansi/Mond#96]
I've just discovered Mond while browsing repositories, I have a few questions regarding sandboxing and performance:
a) Is it possible to limit total number of VM instructions for a script? This is from a context of untrusted code, say I need to limit some script to execute no more than N instructions and then exit.
b) Is it possible to limit maximum depth of recursion?
c) Async/await related to #38, I have not found async/await in the list of keywords, are there any plans to implement this? (possibly by expanding to current syntax).
d) Are there any benchmarks, how does Mond cope with other popular scripting libraries? I'm currently transpiling to Lua-like VM and may be interested to switch should the performance be better.
e) Is it possible to safely sandbox Mond, eg. remove access to some of standard libraries listed on wiki? Can Mond scripts somehow call non-binded C# methods (reflection..) and can this be prevented?

**Comment by Rohansi** [comment]
a) Not exactly. It is possible to force the Mond VM to stop executing by (ab)using the [debugging API](https://github.com/Rohansi/Mond/wiki/Debugging). You can attach the following 'debugger' to the `MondState` when the script takes too long to complete. It will then throw an exception on the next instruction and terminate.
```csharp
class InteruptionDebugger : MondDebugger
{
    public InteruptionDebugger()
    {
        IsBreakRequested = true;
    }

    protected override MondDebugAction OnBreak(MondDebugContext context, int address)
    {
        throw new MondRuntimeException("Script interrupted");
    }
}
```

b) Each `MondState` has a call stack limited to 250 levels: https://github.com/Rohansi/Mond/blob/master/Mond/VirtualMachine/Machine.Stacks.cs#L8 However, calls into C# functions will of course use the normal thread stack so you must consider any possible reentrancy into the VM. These count towards the same limit.

c) Maybe one day but I haven't had the time to work on such a large change recently.

d) I haven't done any. I'd expect it to be slower than Lua but (hopefully) not at the bottom of the charts. I've worked on improving performance but definitely not as much as other languages - plus this is fully C# and doesn't even use `unsafe` (yet?).

e) Yes! Any or all of the standard libraries listed on the wiki can be removed or replaced. Only the standard prototypes cannot be changed. 
```csharp
var state = new MondState
{
    Libraries = new MondLibraryManager
    {
        // empty, or add what you need
    },
};
```
